language: java

jdk: openjdk8

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get update
  - sudo apt-get install -y sed
  - chmod +x @ci/*.sh
  - sh @ci/pre-configure-m2.sh

script:
  - mvn clean install -U
  - mvn deploy
